In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw_books_with_genre.csv")
df.head()

,title,price,availability,rating_word,genre
0,It's Only the Himalayas,Â£45.17,In stock,Two,Travel
1,Full Moon over Noahâs Ark: An Odyssey to Mou...,Â£49.43,In stock,Four,Travel
2,See America: A Celebration of Our National Par...,Â£48.87,In stock,Three,Travel
3,Vagabonding: An Uncommon Guide to the Art of L...,Â£36.94,In stock,Two,Travel
4,Under the Tuscan Sun,Â£37.33,In stock,Three,Travel

In [3]:
df.shape

(781, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 781 entries, 0 to 780
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         781 non-null    object
 1   price         781 non-null    object
 2   availability  781 non-null    object
 3   rating_word   781 non-null    object
 4   genre         781 non-null    object
dtypes: object(5)
memory usage: 30.6+ KB

In [5]:
df.isna().sum()

title           0
price           0
availability    0
rating_word     0
genre           0
dtype: int64

In [6]:
df["price"] = (
    df["price"]
    .str.replace("Â£", "", regex=False)
    .str.replace("£", "", regex=False)
    .astype(float)
)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 781 entries, 0 to 780
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         781 non-null    object
 1   price         781 non-null    float64
 2   availability  781 non-null    object
 3   rating_word   781 non-null    object
 4   genre         781 non-null    object
dtypes: float64(1), object(4)
memory usage: 30.6+ KB

In [9]:
df['rating_word'].value_counts()

rating_word
One      177
Three    159
Five     159
Two      143
Four     143
Name: count, dtype: int64

In [10]:
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

df["rating"] = df["rating_word"].map(rating_map)

In [12]:
df['rating'].value_counts()

rating
1    177
3    159
5    159
2    143
4    143
Name: count, dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 781 entries, 0 to 780
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         781 non-null    object
 1   price         781 non-null    float64
 2   availability  781 non-null    object
 3   rating_word   781 non-null    object
 4   genre         781 non-null    object
 5   rating        781 non-null    int64
dtypes: float64(1), int64(1), object(4)
memory usage: 36.7+ KB

In [14]:
df.drop(columns="rating_word", inplace=True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 781 entries, 0 to 780
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         781 non-null    object
 1   price         781 non-null    float64
 2   availability  781 non-null    object
 3   genre         781 non-null    object
 4   rating        781 non-null    int64
dtypes: float64(1), int64(1), object(3)
memory usage: 30.6+ KB

In [16]:
df["title"] = (
    df["title"]
    .str.replace('Â', '', regex=False)
    .str.replace('�', '', regex=False)
    .str.replace('"', '', regex=False)
    .str.strip()
)

In [17]:
df["title"]

0                                It's Only the Himalayas
1      Full Moon over Noahâs Ark: An Odyssey to Mou...
2      See America: A Celebration of Our National Par...
3      Vagabonding: An Uncommon Guide to the Art of L...
4                                   Under the Tuscan Sun
                             ...
776    Why the Right Went Wrong: Conservatism--From G...
777    Equal Is Unfair: America's Misguided Fight Aga...
778                                       Amid the Chaos
779                                           Dark Notes
780    The Long Shadow of Small Ghosts: Murder and Me...
Name: title, Length: 781, dtype: object

In [20]:
import re
df["title"] = df["title"].apply(
    lambda x: re.sub(r"[^\x00-\x7F]+", "", x)
)

In [21]:
df["title"]

0                                It's Only the Himalayas
1      Full Moon over Noahs Ark: An Odyssey to Mount ...
2      See America: A Celebration of Our National Par...
3      Vagabonding: An Uncommon Guide to the Art of L...
4                                   Under the Tuscan Sun
                             ...
776    Why the Right Went Wrong: Conservatism--From G...
777    Equal Is Unfair: America's Misguided Fight Aga...
778                                       Amid the Chaos
779                                           Dark Notes
780    The Long Shadow of Small Ghosts: Murder and Me...
Name: title, Length: 781, dtype: object

In [48]:
df["genre"].value_counts()

genre
Nonfiction            110
Sequential Art         75
Fiction                65
Young Adult            54
Fantasy                48
Romance                35
Mystery                32
Food and Drink         30
Childrens              29
Historical Fiction     26
Classics               19
Poetry                 19
History                18
Womens Fiction         17
Horror                 17
Science Fiction        16
Science                14
Music                  13
Business               12
Thriller               11
Philosophy             11
Travel                 11
Humor                  10
Autobiography           9
Art                     8
Psychology              7
Religion                7
Christian Fiction       6
New Adult               6
Spirituality            6
Self Help               5
Sports and Games        5
Biography               5
Health                  4
Contemporary            3
Politics                3
Christian               3
Historical              2
Cultural                1
Novels                  1
Erotica                 1
Parenting               1
Short Stories           1
Suspense                1
Academic                1
Adult Fiction           1
Paranormal              1
Crime                   1
Name: count, dtype: int64

In [38]:
genre_map = {
    # Fiction
    "Fiction": "Fiction",
    "Contemporary": "Fiction",
    "Novels": "Fiction",
    "Adult Fiction": "Fiction",
    "Womens Fiction": "Fiction",

    # Fantasy & Sci-Fi
    "Fantasy": "Fantasy & Sci-Fi",
    "Science Fiction": "Fantasy & Sci-Fi",
    "Paranormal": "Fantasy & Sci-Fi",

    # Mystery / Thriller
    "Mystery": "Mystery / Thriller",
    "Thriller": "Mystery / Thriller",
    "Crime": "Mystery / Thriller",
    "Suspense": "Mystery / Thriller",

    # Romance
    "Romance": "Romance",

    # Young Readers
    "Young Adult": "Young Readers",
    "New Adult": "Young Readers",
    "Children": "Young Readers",

    # Non-Fiction
    "Nonfiction": "Non-Fiction",
    "Business": "Non-Fiction",
    "Politics": "Non-Fiction",

    # Philosophy / Religion / Self-help
    "Philosophy": "Philosophy / Religion",
    "Psychology": "Philosophy / Religion",
    "Religion": "Philosophy / Religion",
    "Spirituality": "Philosophy / Religion",
    "Self Help": "Philosophy / Religion",
    "Christian": "Philosophy / Religion",
    "Christian Fiction": "Philosophy / Religion",

    # Arts & Lifestyle
    "Art": "Arts & Lifestyle",
    "Music": "Arts & Lifestyle",
    "Cultural": "Arts & Lifestyle",
    "Food and Drink": "Arts & Lifestyle",
    "Travel": "Arts & Lifestyle",
    "Humor": "Arts & Lifestyle",
    "Sports and Games": "Arts & Lifestyle",
    "Parenting": "Arts & Lifestyle",

    # History & Biography
    "History": "History & Biography",
    "Historical": "History & Biography",
    "Historical Fiction": "History & Biography",
    "Biography": "History & Biography",
    "Autobiography": "History & Biography",

    # Academic
    "Academic": "Academic",
    "Science": "Academic",
    "Health": "Academic",
    # Graphic novels & comics
"Sequential Art": "Graphic Novels & Comics",

# Classics & literature
"Classics": "Classics & Literature",
"Poetry": "Classics & Literature",

# Horror
"Horror": "Horror",

# Academic (ensure these exist)
"Science": "Academic",
"Health": "Academic"
}

In [24]:
genre_group_counts = (
    df["genre_group"]
    .value_counts()
    .rename_axis("genre_group")
    .reset_index(name="count")
)

genre_group_counts

              genre_group  count
0                   Other    161
1             Non-Fiction    125
2                 Fiction     87
3        Arts & Lifestyle     79
4        Fantasy & Sci-Fi     65
5     History & Biography     60
6           Young Readers     60
7      Mystery / Thriller     45
8   Philosophy / Religion     45
9                 Romance     35
10               Academic     19

In [34]:
genre_map ={
    # Graphic novels & comics
"Sequential Art": "Graphic Novels & Comics",

# Classics & literature
"Classics": "Classics & Literature",
"Poetry": "Classics & Literature",

# Horror
"Horror": "Horror",

# Academic (ensure these exist)
"Science": "Academic",
"Health": "Academic"
}

In [39]:
df["genre_group"] = df["genre"].map(genre_map).fillna("Other")

In [40]:
df["genre_group"].value_counts()

genre_group
Non-Fiction                125
Fiction                     87
Arts & Lifestyle            79
Graphic Novels & Comics     75
Fantasy & Sci-Fi            65
History & Biography         60
Young Readers               60
Mystery / Thriller          45
Philosophy / Religion       45
Classics & Literature       38
Romance                     35
Other                       31
Academic                    19
Horror                      17
Name: count, dtype: int64

In [41]:
def map_genre(genre):
    if genre in ["Sequential Art"]:
        return "Graphic Novels & Comics"

    elif genre in [
        "Fiction","Contemporary","Novels","Adult Fiction","Womens Fiction",
        "Classics","Poetry","Historical Fiction"
    ]:
        return "Fiction"

    elif genre in ["Fantasy","Science Fiction","Paranormal","Horror"]:
        return "Speculative Fiction"

    elif genre in ["Mystery","Thriller","Crime","Suspense","Romance"]:
        return "Mystery & Romance"

    elif genre in ["Young Adult","New Adult","Children"]:
        return "Young Readers"

    elif genre in ["Nonfiction","Business","Politics","History",
                   "Biography","Autobiography","Historical"]:
        return "Non-Fiction"

    elif genre in [
        "Philosophy","Psychology","Religion","Spirituality",
        "Self Help","Christian","Christian Fiction"
    ]:
        return "Philosophy / Religion"

    elif genre in [
        "Art","Music","Food and Drink","Travel","Humor",
        "Sports and Games","Parenting","Cultural"
    ]:
        return "Lifestyle & Culture"

    elif genre in ["Academic","Science","Health"]:
        return "Academic"

    else:
        return "Other"

In [42]:
df["genre_group"] = df["genre"].apply(map_genre)
df["genre_group"].value_counts()

genre_group
Non-Fiction                159
Fiction                    151
Speculative Fiction         82
Mystery & Romance           80
Lifestyle & Culture         79
Graphic Novels & Comics     75
Young Readers               60
Philosophy / Religion       45
Other                       31
Academic                    19
Name: count, dtype: int64

In [43]:
def map_genres(genre):
    # ---------- FICTION ----------
    if genre in [
        "Fiction","Contemporary","Novels","Adult Fiction","Womens Fiction"
    ]:
        return "Fiction", "Fiction (Core)"

    elif genre in ["Fantasy","Science Fiction","Paranormal","Horror"]:
        return "Fiction", "Speculative Fiction"

    elif genre in ["Mystery","Thriller","Crime","Suspense","Romance"]:
        return "Fiction", "Mystery & Romance"

    elif genre in ["Classics","Poetry","Historical Fiction"]:
        return "Fiction", "Classics & Literature"

    elif genre in ["Sequential Art"]:
        return "Fiction", "Graphic Novels & Comics"

    # ---------- NON-FICTION ----------
    elif genre in ["Nonfiction","Business","Politics"]:
        return "Non-Fiction", "Non-Fiction (General)"

    elif genre in ["History","Historical","Biography","Autobiography"]:
        return "Non-Fiction", "History & Biography"

    elif genre in [
        "Philosophy","Psychology","Religion","Spirituality",
        "Self Help","Christian","Christian Fiction"
    ]:
        return "Non-Fiction", "Philosophy / Religion"

    # ---------- LIFESTYLE ----------
    elif genre in [
        "Art","Music","Food and Drink","Travel","Humor",
        "Sports and Games","Parenting","Cultural"
    ]:
        return "Lifestyle & Culture", "Lifestyle & Culture"

    # ---------- YOUNG READERS ----------
    elif genre in ["Young Adult","New Adult","Children"]:
        return "Young Readers", "Young Readers"

    # ---------- ACADEMIC ----------
    elif genre in ["Academic","Science","Health"]:
        return "Academic", "Academic"

    # ---------- OTHER ----------
    else:
        return "Other", "Other"


df[["genre_macro", "genre_sub"]] = df["genre"].apply(
    lambda x: pd.Series(map_genres(x))
)

In [44]:
df["genre_macro"].value_counts()

genre_macro
Fiction                388
Non-Fiction            204
Lifestyle & Culture     79
Young Readers           60
Other                   31
Academic                19
Name: count, dtype: int64

In [45]:
df["genre_sub"].value_counts()

genre_sub
Non-Fiction (General)      125
Fiction (Core)              87
Speculative Fiction         82
Mystery & Romance           80
Lifestyle & Culture         79
Graphic Novels & Comics     75
Classics & Literature       64
Young Readers               60
Philosophy / Religion       45
History & Biography         34
Other                       31
Academic                    19
Name: count, dtype: int64

In [46]:
def map_genre_cluster(genre):
    if genre in [
        "Fiction","Contemporary","Novels","Adult Fiction","Womens Fiction",
        "Classics","Poetry"
    ]:
        return "Fiction (General)"

    elif genre in [
        "Fantasy","Science Fiction","Paranormal","Horror",
        "Mystery","Thriller","Crime","Suspense","Romance"
    ]:
        return "Genre Fiction"

    elif genre == "Sequential Art":
        return "Graphic Novels & Comics"

    elif genre in [
        "Nonfiction","Business","Politics",
        "History","Historical","Biography","Autobiography"
    ]:
        return "Non-Fiction"

    elif genre in [
        "Philosophy","Psychology","Religion","Spirituality",
        "Self Help","Christian","Christian Fiction"
    ]:
        return "Philosophy / Religion"

    elif genre in [
        "Art","Music","Food and Drink","Travel","Humor",
        "Sports and Games","Parenting","Cultural"
    ]:
        return "Lifestyle & Culture"

    elif genre in ["Young Adult","New Adult","Children"]:
        return "Young Readers"

    elif genre in ["Academic","Science","Health"]:
        return "Academic"

    else:
        return "Other"


df["genre_cluster"] = df["genre"].apply(map_genre_cluster)
df["genre_cluster"].value_counts()

genre_cluster
Genre Fiction              162
Non-Fiction                159
Fiction (General)          125
Lifestyle & Culture         79
Graphic Novels & Comics     75
Young Readers               60
Other                       57
Philosophy / Religion       45
Academic                    19
Name: count, dtype: int64

In [47]:
def map_genre_cluster(genre):
    if genre in [
        "Fiction","Contemporary","Novels","Adult Fiction","Womens Fiction",
        "Classics","Poetry",
        "Fantasy","Science Fiction","Paranormal","Horror",
        "Mystery","Thriller","Crime","Suspense","Romance"
    ]:
        return "Fiction"

    elif genre == "Sequential Art":
        return "Graphic Novels & Comics"

    elif genre in [
        "Nonfiction","Business","Politics",
        "History","Historical","Biography","Autobiography"
    ]:
        return "Non-Fiction"

    elif genre in [
        "Philosophy","Psychology","Religion","Spirituality",
        "Self Help","Christian","Christian Fiction"
    ]:
        return "Philosophy / Religion / Psychology"

    elif genre in [
        "Art","Music","Food and Drink","Travel","Humor",
        "Sports and Games","Parenting","Cultural"
    ]:
        return "Lifestyle & Culture"

    elif genre in ["Young Adult","New Adult","Children"]:
        return "Young Readers"

    elif genre in ["Academic","Science","Health"]:
        return "Academic"

    else:
        return "Other"


df["genre_cluster"] = df["genre"].apply(map_genre_cluster)
df["genre_cluster"].value_counts()

genre_cluster
Fiction                               287
Non-Fiction                           159
Lifestyle & Culture                    79
Graphic Novels & Comics                75
Young Readers                          60
Other                                  57
Philosophy / Religion / Psychology     45
Academic                               19
Name: count, dtype: int64

In [49]:
df["genre"].value_counts()

genre
Nonfiction            110
Sequential Art         75
Fiction                65
Young Adult            54
Fantasy                48
Romance                35
Mystery                32
Food and Drink         30
Childrens              29
Historical Fiction     26
Classics               19
Poetry                 19
History                18
Womens Fiction         17
Horror                 17
Science Fiction        16
Science                14
Music                  13
Business               12
Thriller               11
Philosophy             11
Travel                 11
Humor                  10
Autobiography           9
Art                     8
Psychology              7
Religion                7
Christian Fiction       6
New Adult               6
Spirituality            6
Self Help               5
Sports and Games        5
Biography               5
Health                  4
Contemporary            3
Politics                3
Christian               3
Historical              2
Cultural                1
Novels                  1
Erotica                 1
Parenting               1
Short Stories           1
Suspense                1
Academic                1
Adult Fiction           1
Paranormal              1
Crime                   1
Name: count, dtype: int64

In [50]:
N = 1
top_genres = df["genre"].value_counts().head(N)
top_genres

genre
Nonfiction            110
Sequential Art         75
Fiction                65
Young Adult            54
Fantasy                48
Romance                35
Mystery                32
Food and Drink         30
Childrens              29
Historical Fiction     26
Name: count, dtype: int64

In [51]:
df["genre_focus"] = df["genre"].apply(
    lambda x: x if x in top_genres.index else "Long Tail"
)

In [52]:
df["genre_focus"].value_counts()

genre_focus
Long Tail             277
Nonfiction            110
Sequential Art         75
Fiction                65
Young Adult            54
Fantasy                48
Romance                35
Mystery                32
Food and Drink         30
Childrens              29
Historical Fiction     26
Name: count, dtype: int64

In [59]:
def map_genre_custom(genre):
    # 1. Non-Fiction (General)
    if genre in [
        "Nonfiction", "Business", "Biography"
    ]:
        return "Non-Fiction (General)"

    # 2. History / Psychology / Human Stories (includes Sequential Art)
    elif genre in [
        "History", "Psychology", "Autobiography", "Self Help", "Sequential Art"
    ]:
        return "History / Psychology / Human Stories"

    # 3. Core Fiction
    elif genre in [
        "Fiction", "Mystery", "Historical Fiction",
        "Womens Fiction", "Science Fiction", "Christian Fiction"
    ]:
        return "Core Fiction"

    # 4. Speculative / Intense Fiction
    elif genre in [
        "Fantasy", "Horror", "Science", "Thriller"
    ]:
        return "Speculative / Intense Fiction"

    # 5. Lifestyle & Light Reads
    elif genre in [
        "Food and Drink", "Travel", "Humor", "Sports and Games", "Health"
    ]:
        return "Lifestyle & Light Reads"

    # 6. Young Adult / New Adult
    elif genre in [
        "Young Adult", "New Adult"
    ]:
        return "Young Adult / New Adult"

    # 7. Romance
    elif genre == "Romance":
        return "Romance"

    # 8. Children
    elif genre == "Childrens":
        return "Children"

    # 9. Arts / Philosophy / Spiritual
    elif genre in [
        "Classics", "Poetry", "Music",
        "Philosophy", "Art", "Religion", "Spirituality"
    ]:
        return "Arts / Philosophy / Spiritual"

    # 10. Other
    else:
        return "Other"

In [60]:
df["genre_group"] = df["genre"].apply(map_genre_custom)

In [61]:
df["genre_group"].value_counts()

genre_group
Core Fiction                            162
Non-Fiction (General)                   127
History / Psychology / Human Stories    114
Speculative / Intense Fiction            90
Arts / Philosophy / Spiritual            83
Lifestyle & Light Reads                  60
Young Adult / New Adult                  60
Romance                                  35
Children                                 29
Other                                    21
Name: count, dtype: int64

In [62]:
df.columns

Index(['title', 'price', 'availability', 'genre', 'rating', 'genre_group',
       'genre_macro', 'genre_sub', 'genre_cluster', 'genre_focus'],
      dtype='object')

In [63]:
df["in_stock"] = df["availability"].str.lower().eq("in stock")
df.drop(columns="availability", inplace=True)

In [64]:
df["title"].isna().sum()

0

In [65]:
df["title"].duplicated().sum()

1

In [66]:
df = df.drop_duplicates(subset="title")

In [67]:
df["genre_group"].value_counts()

genre_group
Core Fiction                            162
Non-Fiction (General)                   127
History / Psychology / Human Stories    114
Speculative / Intense Fiction            89
Arts / Philosophy / Spiritual            83
Lifestyle & Light Reads                  60
Young Adult / New Adult                  60
Romance                                  35
Children                                 29
Other                                    21
Name: count, dtype: int64

In [68]:
df.describe()["price"]

count    780.000000
mean      35.143590
std       14.516895
min       10.000000
25%       22.110000
50%       35.940000
75%       47.820000
max       59.990000
Name: price, dtype: float64

In [69]:
df["rating"].value_counts().sort_index()

rating
1    177
2    143
3    159
4    143
5    158
Name: count, dtype: int64

In [70]:
df["genre"] = df["genre"].str.strip().str.title()

In [71]:
df.columns

Index(['title', 'price', 'genre', 'rating', 'genre_group', 'genre_macro',
       'genre_sub', 'genre_cluster', 'genre_focus', 'in_stock'],
      dtype='object')

In [72]:
df.drop(
    columns=["genre_macro", "genre_sub", "genre_cluster", "genre_focus"],
    inplace=True
)

In [73]:
df.columns

Index(['title', 'price', 'genre', 'rating', 'genre_group', 'in_stock'], dtype='object')

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 780
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        780 non-null    object
 1   price        780 non-null    float64
 2   genre        780 non-null    object
 3   rating       780 non-null    int64
 4   genre_group  780 non-null    object
 5   in_stock     780 non-null    bool
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 37.3+ KB

In [75]:
df.sample(5)

,title,price,genre,rating,genre_group,in_stock
284,Big Little Lies,22.11,Fiction,1,Core Fiction,True
593,A Light in the Attic,51.77,Poetry,3,Arts / Philosophy / Spiritual,True
237,The First Hostage (J.B. Collins #2),25.85,Fiction,3,Core Fiction,True
386,Brazen: The Courage to Find the You That's Bee...,19.22,Nonfiction,2,Non-Fiction (General),True
290,Bright Lines,39.07,Fiction,5,Core Fiction,True

In [83]:
df["price_bucket"] = pd.cut(
    df["price"],
    bins=[0, 15, 30, 45, 60],
    labels=["Low", "Lower-Mid", "Mid", "Upper-Mid"]
)

In [84]:
df.head()

,title,price,genre,rating,genre_group,in_stock,price_bucket
0,It's Only the Himalayas,45.17,Travel,2,Lifestyle & Light Reads,True,Upper-Mid
1,Full Moon over Noahs Ark: An Odyssey to Mount ...,49.43,Travel,4,Lifestyle & Light Reads,True,Upper-Mid
2,See America: A Celebration of Our National Par...,48.87,Travel,3,Lifestyle & Light Reads,True,Upper-Mid
3,Vagabonding: An Uncommon Guide to the Art of L...,36.94,Travel,2,Lifestyle & Light Reads,True,Mid
4,Under the Tuscan Sun,37.33,Travel,3,Lifestyle & Light Reads,True,Mid

In [85]:
df["price_bucket"].value_counts()

price_bucket
Upper-Mid    236
Lower-Mid    232
Mid          226
Low           86
Name: count, dtype: int64

In [86]:
df["price_bucket"] = pd.qcut(
    df["price"],
    q=4,
    labels=["Low", "Mid-Low", "Mid-High", "High"]
)

df["price_bucket"].value_counts()

price_bucket
Low         196
Mid-High    196
Mid-Low     194
High        194
Name: count, dtype: int64

In [87]:
# Absolute price bands (storytelling)
df["price_band"] = pd.cut(
    df["price"],
    bins=[0, 15, 30, 45, 60],
    labels=["Low", "Lower-Mid", "Mid", "Upper-Mid"]
)

# Relative price tiers (analysis)
df["price_tier"] = pd.qcut(
    df["price"],
    q=4,
    labels=["Cheapest", "Mid-Low", "Mid-High", "Most Expensive"]
)

In [88]:
df.head()

,title,price,genre,rating,genre_group,in_stock,price_bucket,price_band,price_tier
0,It's Only the Himalayas,45.17,Travel,2,Lifestyle & Light Reads,True,Mid-High,Upper-Mid,Mid-High
1,Full Moon over Noahs Ark: An Odyssey to Mount ...,49.43,Travel,4,Lifestyle & Light Reads,True,High,Upper-Mid,Most Expensive
2,See America: A Celebration of Our National Par...,48.87,Travel,3,Lifestyle & Light Reads,True,High,Upper-Mid,Most Expensive
3,Vagabonding: An Uncommon Guide to the Art of L...,36.94,Travel,2,Lifestyle & Light Reads,True,Mid-High,Mid,Mid-High
4,Under the Tuscan Sun,37.33,Travel,3,Lifestyle & Light Reads,True,Mid-High,Mid,Mid-High

In [89]:
df.drop(
    columns=["price_bucket"],
    inplace=True
)

In [90]:
df.head()

,title,price,genre,rating,genre_group,in_stock,price_band,price_tier
0,It's Only the Himalayas,45.17,Travel,2,Lifestyle & Light Reads,True,Upper-Mid,Mid-High
1,Full Moon over Noahs Ark: An Odyssey to Mount ...,49.43,Travel,4,Lifestyle & Light Reads,True,Upper-Mid,Most Expensive
2,See America: A Celebration of Our National Par...,48.87,Travel,3,Lifestyle & Light Reads,True,Upper-Mid,Most Expensive
3,Vagabonding: An Uncommon Guide to the Art of L...,36.94,Travel,2,Lifestyle & Light Reads,True,Mid,Mid-High
4,Under the Tuscan Sun,37.33,Travel,3,Lifestyle & Light Reads,True,Mid,Mid-High

In [91]:
df["rating_label"] = df["rating"].map({
    1: "Poor", 2: "Average", 3: "Good", 4: "Very Good", 5: "Excellent"
})

In [93]:
df.head(10)

,title,price,genre,rating,genre_group,in_stock,price_band,price_tier,rating_label
0,It's Only the Himalayas,45.17,Travel,2,Lifestyle & Light Reads,True,Upper-Mid,Mid-High,Average
1,Full Moon over Noahs Ark: An Odyssey to Mount ...,49.43,Travel,4,Lifestyle & Light Reads,True,Upper-Mid,Most Expensive,Very Good
2,See America: A Celebration of Our National Par...,48.87,Travel,3,Lifestyle & Light Reads,True,Upper-Mid,Most Expensive,Good
3,Vagabonding: An Uncommon Guide to the Art of L...,36.94,Travel,2,Lifestyle & Light Reads,True,Mid,Mid-High,Average
4,Under the Tuscan Sun,37.33,Travel,3,Lifestyle & Light Reads,True,Mid,Mid-High,Good
5,A Summer In Europe,44.34,Travel,2,Lifestyle & Light Reads,True,Mid,Mid-High,Average
6,The Great Railway Bazaar,30.54,Travel,1,Lifestyle & Light Reads,True,Mid,Mid-Low,Poor
7,A Year in Provence (Provence #1),56.88,Travel,4,Lifestyle & Light Reads,True,Upper-Mid,Most Expensive,Very Good
8,The Road to Little Dribbling: Adventures of an...,23.21,Travel,1,Lifestyle & Light Reads,True,Lower-Mid,Mid-Low,Poor
9,Neither Here nor There: Travels in Europe,38.95,Travel,3,Lifestyle & Light Reads,True,Mid,Mid-High,Good

In [94]:
df.sample(10)

,title,price,genre,rating,genre_group,in_stock,price_band,price_tier,rating_label
776,Why the Right Went Wrong: Conservatism--From G...,52.65,Politics,4,Other,True,Upper-Mid,Most Expensive,Very Good
537,This Is Where It Ends,27.12,Young Adult,2,Young Adult / New Adult,True,Lower-Mid,Mid-Low,Average
365,Abstract City,56.37,Nonfiction,5,Non-Fiction (General),True,Upper-Mid,Most Expensive,Excellent
147,The Hound of the Baskervilles (Sherlock Holmes...,14.82,Classics,2,Arts / Philosophy / Spiritual,True,Low,Cheapest,Average
620,Ways of Seeing,39.51,Art,5,Arts / Philosophy / Spiritual,True,Mid,Mid-High,Excellent
645,When You Are Engulfed in Flames,30.89,Humor,5,Lifestyle & Light Reads,True,Mid,Mid-Low,Excellent
401,The Geography of Bliss: One Grump's Search for...,28.23,Nonfiction,2,Non-Fiction (General),True,Lower-Mid,Mid-Low,Average
591,Seven Brief Lessons on Physics,30.60,Science,4,Speculative / Intense Fiction,True,Mid,Mid-Low,Very Good
353,The Year of Magical Thinking,43.04,Nonfiction,2,Non-Fiction (General),True,Mid,Mid-High,Average
56,The Passion of Dolssa,28.32,Historical Fiction,5,Core Fiction,True,Lower-Mid,Mid-Low,Excellent